### ISSUE TITLE
Why classified under topic "Log manipulation" on CTAN

### ISSUE THREAD

**Issue by muzimuzhi** [lvjr/texbuildpkg#2]
In my understanding this package has nothing to do with log manipulation, https://ctan.org/topic/log-manip.

At least it fits in topic "Use Lua" https://ctan.org/topic/use-lua.

https://ctan.org/pkg/ppmcheckpdf
<img width="543" alt="image" src="https://github.com/lvjr/ppmcheckpdf/assets/6376638/8c78b5ad-221e-4d42-be04-e02f629702ce">

**Comment by lvjr** [comment]
CTAN people classified it. I can ask them to make the change in next upload.

**Comment by lvjr** [comment]
Now fixed. The ctan page will be regenerated later.
